[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy<2.0.0",
    "pandas>=2.3.3",
    "pillow>=12.0.0",
    "streamlit>=1.52.1",
    "tensorflow==2.15.0",
]
